export enum EmployeeStatus {
  ACTIVE = 'ACTIVE',
  TERMINATED = 'TERMINATED',
  ON_LEAVE = 'ON LEAVE',
  SICK_LEAVE = 'SICK LEAVE',
  LEAVE_OF_ABSENCE = 'LEAVE OF ABSENCE',
  RESIGNED = 'RESIGNED'
}
